services:

  postgres:
    image: postgres:16
    container_name: order-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5431:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: